# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ShareTest
DESTDIR = ../Win32/Release
QT += core gui network script webkit
CONFIG += release
DEFINES += QT_DLL QT_NETWORK_LIB QT_WEBKIT_LIB QT_SCRIPT_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/Release \
    ./../Include
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(ShareTest.pri)
